# Born-Digital Github Actions for ISLE Releases

name: Docker Image CI

# For BD only see branches are ISLE-v.*-dev only e.g. ISLE-v.1.5.3-dev
# ISLE branches should only be master and latest
# This will result in the image {{ IMAGE_REPO_ORG }}/isle-tomcat:ISLE-v.1.5.3-dev
on:
  push:
    branches: [ ISLE-v.*-dev ]
  pull_request:
    branches: [ ISLE-v.*-dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        Default: ${{ github.repository }}
        ref: 'ISLE-v.1.5.3-dev'

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.IMAGE_REPO_ORG }}/isle-tomcat:${{ secrets.ISLE_7_IMAGE_TAG }}
    
    - name: Push the tagged Docker image
      run: docker push ${{ secrets.IMAGE_REPO_ORG }}/isle-tomcat:${{ secrets.ISLE_7_IMAGE_TAG }}

# ICG ISLE build process will also build and tag "latest"
#    - name: Build the latest Docker image
#      run: docker build . --file Dockerfile --tag {{ IMAGE_REPO_ORG }}/isle-tomcat:latest
    
#    - name: Push the latest Docker image
#      run: docker push {{ IMAGE_REPO_ORG }}/isle-tomcat:latest      